### ISSUE TITLE
Missing Assembly Connectors after scale out. 

### ISSUE THREAD

**Issue by stiesssh** [PalladioSimulator/Palladio-Addons-SPD-Metamodel#9]
## Current Behaviour
* Example Model : RMUC 
* Scaling Policy : Scale out by 2 for Data Processing
The requiring Interfaces of new AssemblyContext `DataProcessing_AssemblyContext_4` are not connected.
<img width="934" alt="ass_out" src="https://github.com/PalladioSimulator/Palladio-Addons-SPD-Metamodel/assets/44230629/c3b5284a-c8c6-40e0-b278-0aeb6210f8c5">

## Desired Behaviour 
Everything is connected.

**Comment by klinakuf** [comment]
resolved by #11
